.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. royalbitcoin_qt test_royalbitcoin_qt
clean: FORCE
	$(MAKE) -C .. royalbitcoin_qt_clean test_royalbitcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_royalbitcoin_qt_check
royalbitcoin-qt royalbitcoin-qt.exe: FORCE
	 $(MAKE) -C .. royalbitcoin_qt
